Lovely Rita: EDA

In [1]:
import math
from collections import defaultdict
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import itertools
import random
from dateutil import relativedelta

pd.options.display.max_rows = 100
pd.options.display.max_columns = 100

Static Variables

In [16]:
data_files_01 = [
    "../data/2012complete-output.csv", 
    "../data/2013complete-output.csv", 
    "../data/2014complete-output.csv", 
    "../data/2015complete-output.csv"
]

dtype_01 = {
    'street': str, 
    'city': str, 
    'state': str, 
    'ticket_number': str, 
    'ticket_issue_date': str, 
    'ticket_issue_time': str, 
    'violation_external_code': str,
    'violation_desc_long': str, 
    'street_no': str, 
    'street_name': str, 
    'street_suffix': str,
    'fine_amount': str, 
    'badge__': str, 
    'Unnamed: 13': str, 
    '[sequence]': int, 
    '[summary]': str,
    '[addressee]': str, 
    '[delivery_line_1]': str, 
    '[delivery_line_2]': str,
    '[city_name]': str,
    '[state_abbreviation]': str, 
    '[full_zipcode]': str, 
    '[notes]': str,
    '[county_name]': str, 
    '[rdi]': str, 
    '[latitude]': float, 
    '[longitude]': float,
    '[precision]': str, 
    '[dpv_match_code]': str, 
    '[dpv_footnotes]': str, 
    '[footnotes]': str,
    '[county_fips]': str, 
    '[record_type]': str, 
    '[zip_type]': str, 
    '[carrier_route]': str,
    '[congressional_district]': str, 
    '[building_default_indicator]': str, 
    '[elot_sequence]': str, 
    '[elot_sort]': str, 
    '[time_zone]': str, 
    '[utc_offset]': str,
    '[dst]': str, 
    '[dpv_cmra]': str, 
    '[ews_match]': str, 
    '[lacslink_indicator]': str,
    '[lacslink_code]': str, 
    '[suitelink_match]': str, 
    '[dpv_vacant]': str, 
    '[active]': str,
    '[urbanization]': str, 
    '[primary_number]': str, 
    '[street_name]': str,
    '[street_predirection]': str, 
    '[street_postdirection]': str,
    '[street_suffix]': str, 
    '[secondary_number]': str, 
    '[secondary_designator]': str,
    '[extra_secondary_number]': str, 
    '[extra_secondary_designator]': str,
    '[pmb_designator]': str, 
    '[pmb_number]': str, 
    '[default_city_name]': str,
    '[zipcode]': str, 
    '[plus4_code]': str, 
    '[delivery_point]': str,
    '[delivery_point_check_digit]': str, 
    '[last_line]': str,
    '[delivery_point_barcode]': str
}

column_map_01 = {
    'street': 'Street', 
    'city': 'City', 
    'state': 'State', 
    'ticket_number': 'Ticket Number', 
    'ticket_issue_date': 'Ticket Issue Date', 
    'ticket_issue_time': 'Ticket Issue Time', 
    'violation_external_code': 'Violation External Code',
    'violation_desc_long': 'Violation Description Long', 
    'street_no': 'Street Number', 
    'street_name': 'Street Name', 
    'street_suffix': 'Street Suffix',
    'fine_amount': 'Fine Amount', 
    'badge__': 'Badge Number', 
    'Unnamed: 13': 'Unnamed: 13', 
    '[sequence]': 'Sequence', 
    '[summary]': 'Summary',
    '[addressee]': 'Addressee', 
    '[delivery_line_1]': 'Delivery Line 1', 
    '[delivery_line_2]': 'Delivery Line 2',
    '[city_name]': 'City Name',
    '[state_abbreviation]': 'State Abbreviation', 
    '[full_zipcode]': 'Full Zipcode', 
    '[notes]': 'Notes',
    '[county_name]': 'County Name', 
    '[rdi]': 'RCI', 
    '[latitude]': 'Latitude', 
    '[longitude]': 'Longitude',
    '[precision]': 'Precision', 
    '[dpv_match_code]': 'DPV Match Code', 
    '[dpv_footnotes]': 'DPV Footnotes', 
    '[footnotes]': 'Footnotes',
    '[county_fips]': 'County FIPS', 
    '[record_type]': 'Record Type', 
    '[zip_type]': 'Zip Type', 
    '[carrier_route]': 'Carrier Route',
    '[congressional_district]': 'Congressional District', 
    '[building_default_indicator]': 'Building Default Indicator', 
    '[elot_sequence]': 'eLot Sequence', 
    '[elot_sort]': 'eLot Sort', 
    '[time_zone]': 'Time Zone', 
    '[utc_offset]': 'UTC Offset',
    '[dst]': 'DST', 
    '[dpv_cmra]': 'DPV Camera', 
    '[ews_match]': 'EWS Match', 
    '[lacslink_indicator]': 'LACS Link Indicator',
    '[lacslink_code]': 'LACS Link Code', 
    '[suitelink_match]': 'Suite Link Match', 
    '[dpv_vacant]': 'DPV Vacant', 
    '[active]': 'Active',
    '[urbanization]': 'Urbanization', 
    '[primary_number]': 'Primary Number', 
    '[street_name]': 'Street Name 2',
    '[street_predirection]': 'Street Predirection', 
    '[street_postdirection]': 'Street Postdirection',
    '[street_suffix]': 'Street Suffix 2', 
    '[secondary_number]': 'Secondary Number', 
    '[secondary_designator]': 'Secondary Designator',
    '[extra_secondary_number]': 'Extra Secondary Number', 
    '[extra_secondary_designator]': 'Extra Secondary Designator',
    '[pmb_designator]': 'PMB Designator', 
    '[pmb_number]': 'PMB Number', 
    '[default_city_name]': 'Default City Name',
    '[zipcode]': 'Zipcode', 
    '[plus4_code]': 'Plus 4 Code', 
    '[delivery_point]': 'Delivery Point',
    '[delivery_point_check_digit]': 'Delivery Point Check Digit', 
    '[last_line]': 'Last Line',
    '[delivery_point_barcode]': 'Delivery Point Barcode'
}

data_files_02 = [
    "../data/2016complete-output.csv"
]

dtype_02 = {
    'street': str, 
    'city': str, 
    'state': str, 
    'Ticket Number': str, 
    'Ticket Issue Date': str, 
    'Ticket Issue Time': str, 
    'Violation External Code': str,
    'Violation Desc Long': str, 
    'Street No': str, 
    'Street Name': str, 
    'Street Suffix': str,
    'Fine Amount': str, 
    'Badge #': str, 
    'Unnamed: 13': str, 
    '[sequence]': int, 
    '[summary]': str,
    '[addressee]': str, 
    '[delivery_line_1]': str, 
    '[delivery_line_2]': str,
    '[city_name]': str,
    '[state_abbreviation]': str, 
    '[full_zipcode]': str, 
    '[notes]': str,
    '[county_name]': str, 
    '[rdi]': str, 
    '[latitude]': float, 
    '[longitude]': float,
    '[precision]': str, 
    '[dpv_match_code]': str, 
    '[dpv_footnotes]': str, 
    '[footnotes]': str,
    '[county_fips]': str, 
    '[record_type]': str, 
    '[zip_type]': str, 
    '[carrier_route]': str,
    '[congressional_district]': str, 
    '[building_default_indicator]': str, 
    '[elot_sequence]': str, 
    '[elot_sort]': str, 
    '[time_zone]': str, 
    '[utc_offset]': str,
    '[dst]': str, 
    '[dpv_cmra]': str, 
    '[ews_match]': str, 
    '[lacslink_indicator]': str,
    '[lacslink_code]': str, 
    '[suitelink_match]': str, 
    '[dpv_vacant]': str, 
    '[active]': str,
    '[urbanization]': str, 
    '[primary_number]': str, 
    '[street_name]': str,
    '[street_predirection]': str, 
    '[street_postdirection]': str,
    '[street_suffix]': str, 
    '[secondary_number]': str, 
    '[secondary_designator]': str,
    '[extra_secondary_number]': str, 
    '[extra_secondary_designator]': str,
    '[pmb_designator]': str, 
    '[pmb_number]': str, 
    '[default_city_name]': str,
    '[zipcode]': str, 
    '[plus4_code]': str, 
    '[delivery_point]': str,
    '[delivery_point_check_digit]': str, 
    '[last_line]': str,
    '[delivery_point_barcode]': str
}

column_map_02 = {
    'street': 'Street', 
    'city': 'City', 
    'state': 'State', 
    'Ticket Number': 'Ticket Number', 
    'Ticket Issue Date': 'Ticket Issue Date', 
    'Ticket Issue Time': 'Ticket Issue Time', 
    'Violation External Code': 'Violation External Code',
    'Violation Desc Long': 'Violation Description Long', 
    'Street No': 'Street Number', 
    'Street Name': 'Street Name', 
    'Street Suffix': 'Street Suffix',
    'Fine Amount': 'Fine Amount', 
    'Badge #': 'Badge Number', 
    'Unnamed: 13': 'Unnamed: 13', 
    '[sequence]': 'Sequence', 
    '[summary]': 'Summary',
    '[addressee]': 'Addressee', 
    '[delivery_line_1]': 'Delivery Line 1', 
    '[delivery_line_2]': 'Delivery Line 2',
    '[city_name]': 'City Name',
    '[state_abbreviation]': 'State Abbreviation', 
    '[full_zipcode]': 'Full Zipcode', 
    '[notes]': 'Notes',
    '[county_name]': 'County Name', 
    '[rdi]': 'RCI', 
    '[latitude]': 'Latitude', 
    '[longitude]': 'Longitude',
    '[precision]': 'Precision', 
    '[dpv_match_code]': 'DPV Match Code', 
    '[dpv_footnotes]': 'DPV Footnotes', 
    '[footnotes]': 'Footnotes',
    '[county_fips]': 'County FIPS', 
    '[record_type]': 'Record Type', 
    '[zip_type]': 'Zip Type', 
    '[carrier_route]': 'Carrier Route',
    '[congressional_district]': 'Congressional District', 
    '[building_default_indicator]': 'Building Default Indicator', 
    '[elot_sequence]': 'eLot Sequence', 
    '[elot_sort]': 'eLot Sort', 
    '[time_zone]': 'Time Zone', 
    '[utc_offset]': 'UTC Offset',
    '[dst]': 'DST', 
    '[dpv_cmra]': 'DPV Camera', 
    '[ews_match]': 'EWS Match', 
    '[lacslink_indicator]': 'LACS Link Indicator',
    '[lacslink_code]': 'LACS Link Code', 
    '[suitelink_match]': 'Suite Link Match', 
    '[dpv_vacant]': 'DPV Vacant', 
    '[active]': 'Active',
    '[urbanization]': 'Urbanization', 
    '[primary_number]': 'Primary Number', 
    '[street_name]': 'Street Name 2',
    '[street_predirection]': 'Street Predirection', 
    '[street_postdirection]': 'Street Postdirection',
    '[street_suffix]': 'Street Suffix 2', 
    '[secondary_number]': 'Secondary Number', 
    '[secondary_designator]': 'Secondary Designator',
    '[extra_secondary_number]': 'Extra Secondary Number', 
    '[extra_secondary_designator]': 'Extra Secondary Designator',
    '[pmb_designator]': 'PMB Designator', 
    '[pmb_number]': 'PMB Number', 
    '[default_city_name]': 'Default City Name',
    '[zipcode]': 'Zipcode', 
    '[plus4_code]': 'Plus 4 Code', 
    '[delivery_point]': 'Delivery Point',
    '[delivery_point_check_digit]': 'Delivery Point Check Digit', 
    '[last_line]': 'Last Line',
    '[delivery_point_barcode]': 'Delivery Point Barcode'
}

delimiter = ","

address_file_01 = "../data/addresses_01.txt"
address_file_02 = "../data/addresses_02.txt"

columns_to_drop = [
    "Addressee", 
    "Delivery Line 2", 
    "EWS Match", 
    "Extra Secondary Number", 
    "PMB Designator", 
    "PMB Number", 
    "Suite Link Match", 
    "Unnamed: 13", 
    "Urbanization"
]

Functions

In [56]:
def get_data(data_files, dtype, column_map, delimiter):
    df = pd.concat([pd.read_csv(f, dtype=dtype, delimiter=delimiter) for f in data_files]).reset_index(drop=True)
    df.rename(columns=column_map, inplace=True)
    return df

def get_column_report(df):
    column_report = []
    for column in df.columns:
        unique = df[column].unique()
        sample = np.nan
        for value in unique:
            if value is not np.nan:
                sample = value
                break
        nans = df[column].isnull().sum()
        pct_nan = 100. * nans / df.shape[0]
        column_report.append([column, df[column].dtype, len(unique), sample, nans, pct_nan])
    columns=["Column Name", "Data Type", "Unique Count", "Sample Value", "NaNs", "% NaN"]
    column_report = pd.DataFrame(column_report, columns=columns).round(2)
    column_report.sort_values(by="NaNs", inplace=True)
    return column_report

def get_uniques(df):
    for column in df.columns:
        print column, df[column].unique()
        
def output_addresses(condition, file_out):
    addresses = set()
    for i, item in (df[condition]["Street"] + " " + df[condition]["City"] + " " + df[condition]["State"]).iteritems():
        addresses.add(" ".join(item.lower().split()))
    with open(file_out, 'w') as output:
        for address in addresses:
            output.write(address + '\n')
    return addresses

def convert_time_str_to_min(time_str):
    time_elements = time_str.split(":")
    hours = int(time_elements[0])
    minutes = int(time_elements[1])
    return minutes + (hours * 60)

def convert_min_to_time_str(minutes):
    minutes_str = str(minutes % 60)
    if len(minutes_str) == 1:
        minutes_str = '0' + minutes_str
    return str((minutes / 60) % 24) + ":" + minutes_str
    
def get_time_diff(time_start, time_end):
    time_1 = convert_time_str_to_min(time_start)
    time_2 = convert_time_str_to_min(time_end)
    if time_2 < time_1:
        time_2 += 24 * 60
    return time_2 - time_1

Load Raw Data and Merge

In [4]:
df_01 = get_data(data_files_01, dtype_01, column_map_01, delimiter)
print df_01.shape

(1319187, 68)

In [5]:
df_02 = get_data(data_files_02, dtype_02, column_map_02, delimiter)
df_02 = df_02[:-1] # last row is junk
print df_02.shape

(326625, 68)

In [6]:
df = pd.concat([df_01, df_02]).reset_index(drop=True)
print df.shape
df_01 = None
df_02 = None

(1645812, 68)

In [7]:
get_column_report(df)

,Column Name,Data Type,Unique Count,Sample Value,NaNs,% NaN
55,Ticket Issue Date,object,1827,1/1/12,0,0.00
38,RCI,object,3,Residential,0,0.00
36,Precision,object,5,Zip9,0,0.00
45,Street,object,174339,6100 OLD QUARRY LOOP,0,0.00
31,Longitude,float64,10575,-122.166,0,0.00
30,Latitude,float64,9324,37.7787,0,0.00
54,Summary,object,5,Match-Mailable,0,0.00
43,State,object,2,california,0,0.00
57,Ticket Number,object,1645812,838880801,0,0.00
58,Time Zone,object,2,Pacific,0,0.00
62,Violation Description Long,object,87,OBEDIENCE TO SIGNS,0,0.00
42,Sequence,int64,347427,1,0,0.00
63,Violation External Code,object,98,10.16.110,0,0.00
2,Badge Number,object,1461,937,0,0.00
5,City,object,2,oakland,0,0.00
16,Delivery Line 1,object,164654,6100 Old Quarry Loop,21,0.00
32,Notes,object,64,"Standardized, Matched street and city and stat...",21,0.00
29,Last Line,object,20025,Oakland CA 94605-3376,21,0.00
11,DPV Footnotes,object,9,AABB,21,0.00
6,City Name,object,3,Oakland,21,0.00
44,State Abbreviation,object,2,CA,21,0.00
46,Street Name,object,8579,OLD QUARRY LOOP,25,0.00
56,Ticket Issue Time,object,2872,10:30:00,119,0.01
24,Fine Amount,object,68,$73,408,0.02
48,Street Number,object,10859,6100,27800,1.69
51,Street Suffix,object,18,AVE,71187,4.33
7,Congressional District,object,3,13,219555,13.34
47,Street Name 2,object,1263,Old Quarry,219555,13.34
8,County FIPS,object,2,06001,219555,13.34
4,Carrier Route,object,53,C026,219555,13.34
9,County Name,object,2,Alameda,219555,13.34
59,UTC Offset,object,2,-8,219555,13.34
39,Record Type,object,4,S,219555,13.34
14,DST,object,2,Y,219555,13.34
26,Full Zipcode,object,20024,94605-3376,222599,13.53
19,Delivery Point Barcode,object,83474,946053376007,222599,13.53
64,Zip Type,object,3,Standard,222599,13.53
65,Zipcode,object,18,94605,222599,13.53
37,Primary Number,object,9223,6100,223544,13.58
12,DPV Match Code,object,5,Y,223588,13.59
35,Plus 4 Code,object,4324,3376,223588,13.59
52,Street Suffix 2,object,21,Loop,247585,15.04
0,Active,object,3,Y,648642,39.41
67,eLot Sort,object,3,D,648642,39.41
13,DPV Vacant,object,3,N,648642,39.41
66,eLot Sequence,object,377,0220,648642,39.41
18,Delivery Point,object,101,00,648642,39.41
20,Delivery Point Check Digit,object,11,7,648642,39.41
10,DPV Camera,object,3,N,648642,39.41
25,Footnotes,object,38,L#,995274,60.47
3,Building Default Indicator,object,2,Y,1422931,86.46
50,Street Predirection,object,5,E,1533810,93.19
15,Default City Name,object,3,Emeryville,1574641,95.68
40,Secondary Designator,object,11,Lot,1629637,99.02
27,LACS Link Code,object,3,00,1638024,99.53
28,LACS Link Indicator,object,3,N,1638024,99.53
49,Street Postdirection,object,5,E,1643655,99.87
41,Secondary Number,object,50,12,1644057,99.89
22,Extra Secondary Designator,object,2,Lot,1645788,100.00
1,Addressee,object,1,NaN,1645812,100.00
61,Urbanization,object,1,NaN,1645812,100.00
21,EWS Match,object,1,NaN,1645812,100.00
17,Delivery Line 2,object,1,NaN,1645812,100.00
53,Suite Link Match,object,1,NaN,1645812,100.00
23,Extra Secondary Number,object,1,NaN,1645812,100.00
34,PMB Number,object,1,NaN,1645812,100.00
60,Unnamed: 13,object,1,NaN,1645812,100.00
33,PMB Designator,object,1,NaN,1645812,100.00

Unique IDs:
Ticket Number
Sequence (with Year)

Empty columns:
Addressee
Delivery Line 2
EWS Match
Extra Secondary Number
PMB Designator
PMB Number
Suite Link Match
Unnamed: 13
Urbanization

Invariant information columns:
County FIPS
County Name
State
State Abbreviation
Time Zone
UTC Offset

'> 80% NaN column:
Building Default Indicator
Default City Name
Extra Secondary Designator
LACS Link Code
LACS Link Indicator
Secondary Designator
Secondary Number
Street Postdirection
Street Predirection

Location Parity Analysis

Location columns:
Street
City
State

Street Number
Street Name
Street Suffix

Delivery Line 1
City Name
State Abbreviation
Full Zipcode

Latitude
Longitude

Primary Number
Street Name 2
Street Suffix 2
Zipcode
Plus 4 Code
Last Line

In [8]:
count = 0
for i, row in df.iterrows():
    street_tokens = row["Street"].strip().split()
    s_zeroes = []
    if len(street_tokens) > 0:
        if len(street_tokens[0]) > 0:
            s_zero = street_tokens[0]
            s_zeroes.append(s_zero)
            if s_zero == 'ONE':
                s_zero = '1'
                s_zeroes.append(s_zero)
            elif s_zero == 'TENTH':
                s_zero = '10'
                s_zeroes.append(s_zero)
            elif (s_zero == 'SOUTHWEST') | (s_zero == '#'):
                s_zeroes.append(street_tokens[1])
            elif not s_zero[0].isdigit():
                s_zero = s_zero[1:]
                s_zeroes.append(s_zero)
            if (len(street_tokens) > 3):
                s_one = street_tokens[1]
                if len(s_one) == 2:
                    if not s_one[0].isalpha():
                        s_one = s_one[1:]
                    elif not s_one[1].isalpha():
                        s_one = s_one[:1]
                if (len(s_one) == 1) & s_one.isalpha() & (s_one not in ['N', 'S', 'E', 'W']):
                    s_zeroes.append(s_zero + s_one)
                    s_zeroes.append(s_zero + " " + s_one)
    if type(row["Primary Number"]) != float:
        if row["Primary Number"].strip() not in s_zeroes:
            count += 1
            print row["Primary Number"], " | ", row["Street"], " | ", s_zeroes
print count

3236  |  3238 GRAND AVE  |  ['3238']
503  |  501 FOREST ST  |  ['501']
3236  |  3238 GRAND AVE  |  ['3238']
503  |  501 FOREST ST  |  ['501']
503  |  501 FOREST ST  |  ['501']
503  |  501 FOREST ST  |  ['501']
3236  |  3238 GRAND AVE  |  ['3238']
503  |  501 FOREST ST  |  ['501']
503  |  501 FOREST ST  |  ['501']
3236  |  3238 GRAND AVE  |  ['3238']
503  |  501 FOREST ST  |  ['501']
11

There are 11 rows in which "Primary Number" is not in parity with "Street".

In [9]:
count = 0
for i, row in df.iterrows():
    if type(row["Street Name 2"]) != float:
        street_tokens = row["Street"].strip().split()
        street_names = []
        street_name = " ".join(street_tokens[1:-1]).lower()
        street_names.append(street_name)
        if street_tokens[-1] == 'BROADWAY':
            street_names.append("broadway")
        elif street_tokens[-1] == "INTERNATIONAL":
            street_names.append("international")
        elif street_name == "martin l king jr":
            street_names.append("martin luther king jr")
        elif street_name == "sancarlos":
            street_names.append("san carlos")
        elif street_name == "agua vista":
            street_names.append("aqua vista")
        elif street_name == "iselton":
            street_names.append("isleton")
        elif street_name == "lake shore":
            street_names.append("lakeshore")
        elif street_name == "bay view":
            street_names.append("bayview")
        elif (street_name == "grand ave") | (street_name == "west grand"):
            street_names.append("grand")
        elif street_name == "thomas l":
            street_names.append("thomas l berkley")
        elif len(street_tokens) > 1:
            if street_tokens[1] == "MC":
                street_names.append((street_tokens[1] + street_tokens[2]).lower())
        elif street_name == "benevenue":
            street_names.append("benvenue")
        elif street_name == "23":
            street_names.append("23rd")
        if row["Street Name 2"].lower() not in street_names:
            count += 1
            # print row["Street Name 2"], " | ", row["Street"], " | ", street_names
print count

31528

Street Name Parity Check: Still In Progress

Export unique addresses for Geocode lookup
Two priority orders will be: 1) addresses without Lat/Long data and 2) addresses with Lat/Long data.

In [25]:
addresses_01 = output_addresses((df["Latitude"]==0), address_file_01)
addresses_02 = output_addresses((df["Latitude"]!=0), address_file_02)
print len(set(addresses_01)), len(set(addresses_02))

33835 140490

DateTime Analysis

In [11]:
print df["Ticket Issue Date"].isnull().sum(), df["Ticket Issue Time"].isnull().sum()

0 119

In [12]:
(np.diff(np.where(df["Ticket Issue Time"].isnull()))<=1).sum()

8

There are 0 missing dates and 119 missing times.
Since the data is recorded in temporal order, the times in the neighboring rows represent a window in which the missing time exists.  We can impute the missing time values as the mean time of the neighboring rows.  There are 8 cases where missing values are next to eachother.  For those, we can find the next existing value, and divide the time evenly to fill in the missing values.

In [13]:
get_uniques(df)

Active ['Y' nan 'N']
Addressee [nan]
Badge Number ['937' '8961' '1855' ..., '9442' '201108' '9538']
Building Default Indicator [nan 'Y']
Carrier Route ['C026' 'C001' nan 'C021' 'C007' 'C008' 'C020' 'C016' 'C004' 'C003' 'C014'
 'C005' 'C010' 'C002' 'C011' 'C023' 'C024' 'C033' 'C027' 'C029' 'C037'
 'C034' 'C012' 'C036' 'C015' 'C067' 'C019' 'C018' 'C025' 'C032' 'C013'
 'C022' 'C017' 'C047' 'C006' 'C061' 'C039' 'C009' 'C031' 'C028' 'C035'
 'C030' 'C068' 'C065' 'C770' 'C000' 'C063' 'C038' 'C066' 'C064' 'C040'
 'C058' 'C043']
City ['oakland' 'Oakland']
City Name ['Oakland' 'Piedmont' nan]
Congressional District ['13' nan '11']
County FIPS ['06001' nan]
County Name ['Alameda' nan]
DPV Camera ['N' nan 'Y']
DPV Footnotes ['AABB' 'A1' 'AAN1' 'AAM3' 'A1M1' 'AABBR1' 'AA' 'AACC' nan]
DPV Match Code ['Y' nan 'D' 'N' 'S']
DPV Vacant ['N' nan 'Y']
DST ['Y' nan]
Default City Name [nan 'Emeryville' 'Oakland']
Delivery Line 1 ['6100 Old Quarry Loop' '1800 E 12th St' '300 Oak Coliseum' ...,
 '1833 International Blvd' '1452 High St' '4021 Bayo St']
Delivery Line 2 [nan]
Delivery Point ['00' nan '99' '01' '27' '21' '30' '46' '62' '98' '26' '69' '25' '24' '10'
 '12' '06' '16' '83' '67' '15' '20' '95' '45' '19' '91' '55' '60' '51' '75'
 '65' '35' '68' '33' '17' '13' '31' '52' '49' '70' '29' '32' '34' '44' '50'
 '86' '64' '08' '37' '80' '66' '07' '41' '88' '84' '59' '63' '11' '42' '09'
 '56' '36' '05' '18' '02' '53' '03' '58' '47' '40' '14' '23' '22' '48' '72'
 '28' '39' '93' '76' '85' '38' '97' '77' '78' '82' '94' '43' '90' '54' '61'
 '87' '04' '96' '89' '74' '57' '73' '79' '92' '71' '81']
Delivery Point Barcode ['946053376007' '946064820001' nan ..., '946071644' '946081317146'
 '946192101214']
Delivery Point Check Digit ['7' '1' nan '2' '9' '6' '8' '0' '3' '5' '4']
EWS Match [nan]
Extra Secondary Designator [nan 'Lot']
Extra Secondary Number [nan]
Fine Amount ['$73' '$263' '$66' '$83' '$156' '$513' '$58' '$63' '$103' '$53' '$93'
 '$78' '$283' '$113' '$88' '$368' '$68' '$43' '$80' nan '$265' '$371' '$45'
 '$48' '$316' '$176' '$273' '$153' '$146' '$171' '$346' '$249' '$41' '$38'
 '$196' '$229' '$216' '$186' '$126' '$166' '$454' '$149' '$139' '$114'
 '$239' '$75' '$116' '$119' '$209' '$167' '$136' '$201' '$161' '$288'
 '$128' '$214' '$376' '$151' '$259' '$159' '$269' '$154' '$121' '$85'
 '$254' '$141' '$444' '$131']
Footnotes [nan 'L#' 'F#' 'H#N#' 'H#' 'P#' 'H#L#' 'N#' 'LI#' 'M#' 'E#I#' 'L#P#' 'H#M#'
 'I#' 'D#L#' 'L#M#' 'LI#H#P#' 'LI#N#' 'H#P#' 'I#T#' 'I#K#' 'LI#H#' 'H#L#M#'
 'LI#H#N#' 'LI#H#L#' 'LI#L#' 'LI#P#' 'H#N#P#' 'LI#M#' 'D#' 'H#L#P#' 'N#S#'
 'L#S#' 'E#I#T#' 'N#P#' 'LI#H#M#' 'H#M#P#' 'S#']
Full Zipcode ['94605-3376' '94606-4820' nan ..., '94603-1066' '94605-4009' '94610-2855']
LACS Link Code [nan '00' 'A']
LACS Link Indicator [nan 'N' 'Y']
Last Line ['Oakland CA 94605-3376' 'Oakland CA 94606-4820' 'Oakland CA' ...,
 'Oakland CA 94603-1066' 'Oakland CA 94605-4009' 'Oakland CA 94610-2855']
Latitude [ 37.77874  37.78621   0.      ...,  37.84256  37.7854   37.7598 ]
Longitude [-122.16624 -122.2426     0.      ..., -122.24259 -122.25752 -122.19094]
Notes [ 'Standardized, Matched street and city and state, Confirmed entire address'
 'Standardized, Address component was changed, Matched street and city and state, Confirmed entire address'
 'Address not found, ZIP+4 did not match'
 'Standardized, Missing secondary number, Fixed abbreviations, Matched street and city and state, Confirmed without secondary'
 'Standardized, Missing secondary number, Matched street and city and state, Confirmed without secondary'
 'Standardized, Better address exists, Matched street and city and state, Confirmed entire address'
 'Matched street and city and state, Primary number invalid'
 'Address component was changed, Matched street and city and state, Primary number invalid'
 'Standardized, Missing secondary number, Address component was changed, Matched street and city and state, Confirmed without secondary'
 'Standardized, Fixed abbreviations, Matched street and city and state, Confirmed entire address'
 'Standardized, Flagged for LACSLink, Matched street and city and state, Confirmed entire address'
 'Fixed abbreviations, Matched street and city and state, Primary number invalid'
 'Address not found, ZIP+4 did not match, Primary number missing'
 'Standardized, Fixed street spelling, Matched street and city and state, Confirmed entire address'
 'Same ZIP for multiple, Insufficient data, ZIP+4 did not match, Primary number missing'
 'Standardized, Address component was changed, Better address exists, Matched street and city and state, Confirmed entire address'
 'Standardized, Matched street and city and state, Confirmed entire address, Confirmed without private mailbox'
 'Fixed street spelling, Matched street and city and state, Primary number invalid'
 'Standardized, Missing secondary number, Fixed street spelling, Matched street and city and state, Confirmed without secondary'
 'Insufficient data, ZIP+4 did not match'
 'Better address exists, Matched street and city and state, Primary number invalid'
 'No ZIP+4 assigned, Address component was changed, Matched street and city and state'
 'Address component was changed, Fixed street spelling, Matched street and city and state, Primary number invalid'
 'Standardized, Flagged for LACSLink, Missing secondary number, Better address exists, Matched street and city and state, Confirmed without secondary'
 'Flagged for LACSLink, Fixed abbreviations, Matched street and city and state, Primary number invalid'
 'Flagged for LACSLink, Matched street and city and state, Primary number invalid'
 'Standardized, Missing secondary number, Better address exists, Matched street and city and state, Confirmed without secondary'
 'Standardized, Insufficient data, Magnet street syndrome, Matched street and city and state, Confirmed without secondary'
 'Insufficient data, Cardinal rule match, ZIP+4 did not match'
 'Insufficient data, ZIP+4 did not match, Primary number missing'
 'Standardized, Flagged for LACSLink, Missing secondary number, Matched street and city and state, Confirmed without secondary'
 'Address component was changed, Better address exists, Matched street and city and state, Primary number invalid'
 'Standardized, Address component was changed, Fixed street spelling, Matched street and city and state, Confirmed entire address'
 'Standardized, Missing secondary number, Address component was changed, Fixed street spelling, Matched street and city and state, Confirmed without secondary'
 'Standardized, Flagged for LACSLink, Missing secondary number, Fixed abbreviations, Matched street and city and state, Confirmed without secondary'
 'Standardized, Insufficient data, Matched street and city and state, Confirmed entire address'
 'Standardized, Flagged for LACSLink, Missing secondary number, Address component was changed, Matched street and city and state, Confirmed without secondary'
 'Flagged for LACSLink, Address component was changed, Matched street and city and state, Primary number invalid'
 'Standardized, Insufficient data, Magnet street syndrome, Matched street and city and state, Confirmed entire address'
 'Flagged for LACSLink, Better address exists, Matched street and city and state, Primary number invalid'
 'Standardized, Insufficient data, Matched street and city and state, Confirmed without secondary'
 'Insufficient data, Magnet street syndrome, ZIP+4 did not match, Primary number missing'
 'Standardized, Same ZIP for multiple, Insufficient data, Matched street and city and state, Confirmed without secondary'
 'Standardized, Flagged for LACSLink, Fixed abbreviations, Matched street and city and state, Confirmed entire address'
 'Insufficient data, Magnet street syndrome, ZIP+4 did not match'
 'Standardized, Flagged for LACSLink, Address component was changed, Matched street and city and state, Confirmed entire address'
 'Standardized, Missing secondary number, Fixed abbreviations, Better address exists, Matched street and city and state, Confirmed without secondary'
 'Standardized, Fixed abbreviations, Matched street and city and state, Confirmed by dropping secondary'
 nan
 'Standardized, Flagged for LACSLink, Fixed street spelling, Matched street and city and state, Confirmed entire address'
 'Same ZIP for multiple, Insufficient data, ZIP+4 did not match'
 'Standardized, Address component was changed, Matched street and city and state, Confirmed by dropping secondary'
 'No ZIP+4 assigned, Matched street and city and state'
 'Standardized, Missing secondary number, Address component was changed, Better address exists, Matched street and city and state, Confirmed without secondary'
 'Standardized, Address component was changed, Matched street and city and state, Confirmed entire address, Confirmed without private mailbox'
 'Standardized, Fixed abbreviations, Bad secondary address, Matched street and city and state, Confirmed by dropping secondary'
 'Standardized, Address component was changed, Bad secondary address, Matched street and city and state, Confirmed by dropping secondary'
 'Same ZIP for multiple, Insufficient data, Magnet street syndrome, ZIP+4 did not match, Primary number missing'
 'Fixed abbreviations, Better address exists, Matched street and city and state, Primary number invalid'
 'Standardized, Flagged for LACSLink, Missing secondary number, Fixed street spelling, Matched street and city and state, Confirmed without secondary'
 'Standardized, Missing secondary number, Fixed street spelling, Better address exists, Matched street and city and state, Confirmed without secondary'
 'Standardized, Matched street and city and state, Confirmed by dropping secondary'
 'Standardized, Bad secondary address, Matched street and city and state, Confirmed by dropping secondary'
 'Standardized, Fixed abbreviations, Better address exists, Matched street and city and state, Confirmed entire address']
PMB Designator [nan]
PMB Number [nan]
Plus 4 Code ['3376' '4820' nan ..., '1487' '5298' '3793']
Precision ['Zip9' 'Unknown' 'Zip8' 'Zip5' 'Zip7']
Primary Number ['6100' '1800' nan ..., '8298' '8299' '8297']
RCI ['Residential' 'Commercial' 'Unknown']
Record Type ['S' nan 'H' 'F']
Secondary Designator [nan 'Lot' '#' 'Ste' 'Apt' 'Stop' 'Side' 'Rear' 'Bldg' 'Fl' 'Rm']
Secondary Number [nan '12' '19' '14' 'B' 'A' '6' 'D' '11' '15' 'C' '17' '18' '9' '8' '10'
 '7' '30' '13' 'T-2' '29' '31' 'D4' 'E4' 'G5' 'G7' '41' '40' '2' '21' '1'
 '1210' '66' '47' '24' '37' '39' '3' '5' 'T2' '23' '4788' 'AVENUE1' 'G'
 'DRIVE21' 'DR206AP' '4850' 'AVENUE4' '32' 'ST4867']
Sequence [     1      2      3 ..., 347425 347426 347427]
State ['california' 'California']
State Abbreviation ['CA' nan]
Street ['6100 OLD QUARRY LOOP ' '1800 12TH AVE' '300 OAK COLISEUM ' ...,
 '1833 INTERNATIONAL BLVD' '1452 HIGH ST' '4021 BAYO ST']
Street Name ['OLD QUARRY LOOP' '12TH' 'OAK COLISEUM' ..., 'A-1817 3RD' 'ALOT-810 3RD'
 'ALOT-816 3RD']
Street Name 2 ['Old Quarry' '12th' nan ..., 'Neva' 'Mountain View' 'Doncaster']
Street Number ['6100' '1800' '300' ..., '8298' '8299' '8297']
Street Postdirection [nan 'E' 'W' 'S' 'N']
Street Predirection [nan 'E' 'W' 'S' 'N']
Street Suffix [nan 'AVE' 'DRIVE' 'ST' 'BLVD' 'PLACE' 'ROAD' 'COURT' 'LOT' 'LANE' 'CIR'
 'PLAZA' 'TERR' 'PARK' 'BLOCK' 'PKWY' 'SQ' 'BLD']
Street Suffix 2 ['Loop' 'St' nan 'Dr' 'Way' 'Blvd' 'Ave' 'Pl' 'Rd' 'Ct' 'Pkwy' 'Ln' 'Ter'
 'Cir' 'Plz' 'Crst' 'Cv' 'Aly' 'Vw' 'Sq' 'Hl']
Suite Link Match [nan]
Summary ['Match-Mailable' 'No Match' 'Match-Inactive' 'Match-Vacant'
 'No Match - PO Box Only']
Ticket Issue Date ['1/1/12' '1/2/12' '1/3/12' ..., '12/29/16' '12/30/16' '12/31/16']
Ticket Issue Time ['10:30:00' '12:00:00' '13:50:00' ..., '6:24' '23:54' '7:09']
Ticket Number ['838880801' '838907806' '839915330' ..., '1722312852' '1722327040'
 '809290230']
Time Zone ['Pacific' 'None']
UTC Offset ['-8' nan]
Unnamed: 13 [nan]
Urbanization [nan]
Violation Description Long ['OBEDIENCE TO SIGNS' 'COMM VEH IN RESIDENT' 'NO VALID REG'
 'NO PARK CERTAIN HRS' 'CURRENT TAB NOT ATTA' 'NO PKG WHITE ZONE'
 'NO PKG YELLOW ZONE' 'MISUSE DP' 'NO PARKING RED ZONE'
 'NO PKG - CROSSWALK' 'EXPIRED METER' 'NO PARKING ANYTIME'
 'RIGHT HAND CURB DIST' 'NON DISP PKG RECEIPT' 'NO PKG - SIDEWALK'
 'OVER SPACE MRKG METR' 'METER EXP OFF STREET' 'TWO HOUR ZONE'
 'REMOVAL PRIVATE PROP' 'NO PKG GREEN ZONE' 'RESIDENTIAL PARKING'
 'LICENSE PLATE MISSIN' 'OVER 18IN FROM CURB' 'OBSTRUCT CONST TRAFF'
 'FIRE HYDRANT' 'DOUBLE PARKING' 'NO PKG - TAXI ZONE' 'IMPROP PKG-WHEELCHR'
 'OVER SPACE MARKING' 'IMPROPER PARKING' 'ONE HOUR ZONE'
 'NO PKG - DRIVEWAY' 'DISABLED PERSON PARK' 'METER - OVERTIME'
 'PKG ON PUBLIC GROUND' 'FAIL REMOVE ABAN VEH' 'FOUR HOUR ZONE'
 'NO PARK IN PARKWAY' 'RIGHT-HAND CURB DIST' 'VEHICLE ABANDONMENT'
 'FOR SALE SIGN PUB ST' 'NO VIOLATION CODE' 'UNATTACHED TRAILER'
 'NO PKG - FIRE LANE' 'NO PARKING BUS STOP' 'NO STOPPING/PARKING'
 'ANGLE PARKING UNLOAD' 'IMPROPER LENDING DP' 'PKG WRONG SIDE ROAD'
 'OBSTRUCTION BIKELANE' 'ABANDONED USING STRE' 'COMM VEH 7-10K LBS'
 'USE COUNTERFEIT DP' 'IMPROPER DISPLAY DP' "3' SIDEWALK ACCESS"
 'DP - HATCHMARKS' 'PARKING FOR OFFICIAL' 'NO PKG -  STATE HWY'
 'ANGLE PKG W/IN MARKS' 'NO PARK 3 AM - 6 AM' 'PARK PROHIB TALL VEH'
 'PARKED IN BUS ZONE' 'SPC ZONE - SIGN POST' 'TRAFFIC IN PARKS'
 'NO PKG INTERSECTION' 'REG DISP - WRONG VEH' 'PARALLEL PARKING'
 'NO PKG- SAFETY ZONE' 'IMPEDING TRAFFIC LAN' 'PARKING BY PERMIT'
 'IMPROPER PLATE POSIT' 'OFF CARS OPD/COUNTY' 'ABANDONED VEHICLE'
 'OFF CARS CITY HALL' 'PARK ON PRIVATE PROP' 'EMERGENCY NO PARKING'
 'PARKED WRONG WAY ON' "NO PKG - 15' FIRE ST" 'FAIL TO ACTIVATE MTR'
 'KEY IN IGNITION' 'PARK WRONG WAY 1-WAY' 'NO PKG - RAIL TRACKS'
 'DEFECTIVE WINDOW' 'NO PARKING - FREEWAY' 'FAIL TO CRAMP WHEEL'
 'WHEELS NOT BLOCKED' 'OFFICIAL CARS FD']
Violation External Code ['10.16.110' '10.28.120' '4000A' '10.28.240' '5204' '10.40.070' '10.40.060'
 '4461.D' '10.40.020A1' '22500.B' '10.36.050' '10.28.250' '22502'
 '10.36.030B' '22500.F' '10.36.020' '10.36.100' '10.28.190' '22658.A'
 '10.40.020A4' '10.44.120A' '5200' '10.28.040A' '22500.G' '22514' '22500.H'
 '10.40.110' '22500.L' '10.28.040D' '22500' '10.28.180' '22500.E' '22507.8'
 '10.36.060' '21113.A' '10.64.180' '10.28.210' '5204.A' '10.28.020'
 '22502.A' '22523.A' '12.24.070B' 'NO VIOL' '10.28.160' '22500.1'
 '10.40.090E' '10.28.080' '10.28.060' '4461.B' '22502.E' '21211.B'
 '22507.8A' '10.28.030' '10.28.130' '4463.C' '4461.C' '22522' '22507.8C'
 '10.32.150' '22505.B' '10.28.050' '10.28.260' '10.28.170' '22500.I'
 '10.40.030B' '10.32.180' '22500.A' '4462.B' '10.56.350' '22500.C'
 '10.08.150' '10.32.170' '4000' '5201' '22507.8B' '22523' '10.32.100'
 '10.64.170' '10.40.020' '10.32.030' '10.16.070' '10.28.100' '5200.A'
 '4000A1' '10.28.040B' '22500.D' '12.24.070' '10.36.030' '10.28.150'
 '10.56.330' '10.28.040' '22521' '267.1' '22520' '10.16.090' '22515'
 '10.32.130' '10.32.140']
Zip Type ['Standard' nan 'POBox']
Zipcode ['94605' '94606' nan '94621' '94612' '94609' '94610' '94608' '94602'
 '94619' '94601' '94618' '94611' '94607' '94603' '94615' '94613' '94624']
eLot Sequence ['0220' '0112' nan '0077' '0200' '0206' '0208' '0179' '0202' '0160' '0086'
 '0114' '0099' '0089' '0050' '0079' '0027' '0168' '0127' '0053' '0167'
 '0043' '0178' '0075' '0087' '0046' '0204' '0219' '0040' '0062' '0151'
 '0143' '0242' '0009' '0080' '0002' '0090' '0235' '0069' '0004' '0073'
 '0032' '0229' '0071' '0311' '0015' '0194' '0268' '0061' '0060' '0097'
 '0232' '0017' '0093' '0092' '0138' '0106' '0117' '0108' '0036' '0102'
 '0056' '0115' '0187' '0051' '0047' '0023' '0094' '0109' '0103' '0101'
 '0088' '0031' '0058' '0131' '0145' '0111' '0091' '0147' '0123' '0137'
 '0124' '0130' '0021' '0041' '0078' '0119' '0012' '0095' '0185' '0141'
 '0013' '0054' '0008' '0104' '0191' '0176' '0059' '0113' '0074' '0175'
 '0005' '0048' '0081' '0207' '0209' '0148' '0001' '0016' '0020' '0025'
 '0186' '0010' '0045' '0022' '0129' '0193' '0192' '0055' '0003' '0066'
 '0082' '0083' '0068' '0165' '0183' '0118' '0011' '0107' '0030' '0049'
 '0164' '0182' '0028' '0024' '0330' '0019' '0034' '0035' '0007' '0323'
 '0070' '0018' '0039' '0180' '0100' '0121' '0026' '0098' '0038' '0216'
 '0172' '0215' '0196' '0212' '0211' '0241' '0063' '0064' '0072' '0218'
 '0120' '0042' '0195' '0201' '0247' '0221' '0253' '0057' '0244' '0254'
 '0263' '0174' '0052' '0033' '0224' '0255' '0157' '0166' '0171' '0252'
 '0267' '0199' '0170' '0173' '0142' '0084' '0188' '0158' '0153' '0140'
 '0144' '0161' '0146' '0133' '0203' '0044' '0155' '0365' '0152' '0149'
 '0110' '0225' '0128' '0122' '0067' '0037' '0132' '0065' '0169' '0177'
 '0310' '0324' '0217' '0029' '0014' '0126' '0227' '0139' '0197' '0245'
 '0239' '0228' '0284' '0222' '0205' '0162' '0210' '0277' '0213' '0134'
 '0243' '0240' '0230' '0233' '0236' '0261' '0319' '0251' '0105' '0116'
 '0269' '0276' '0275' '0006' '0309' '0135' '0150' '0246' '0281' '0303'
 '0085' '0332' '0279' '0308' '0159' '0096' '0315' '0154' '0272' '0259'
 '0291' '0292' '0226' '0198' '0327' '0266' '0189' '0184' '0181' '0313'
 '0256' '0294' '0163' '0271' '0248' '0305' '0238' '0237' '0076' '0156'
 '0355' '0373' '0278' '0214' '0250' '0302' '0231' '0262' '0306' '0286'
 '0290' '0340' '0125' '0223' '0297' '0301' '0136' '0342' '0280' '0190'
 '0307' '0249' '0257' '0299' '0318' '0234' '0304' '0260' '0350' '0326'
 '0300' '0296' '0273' '0347' '0282' '0357' '0287' '0270' '0369' '0258'
 '0343' '0333' '0316' '0265' '0264' '0283' '0335' '0370' '0289' '0285'
 '0298' '0274' '0293' '0325' '0321' '0352' '0356' '0312' '0288' '0338'
 '0353' '0348' '0378' '0322' '0344' '0349' '0346' '0314' '0295' '0341'
 '0367' '0336' '0359' '0371' '0345' '0364' '0329' '0328' '0361' '0379'
 '0337' '0331' '0317' '0377' '0354' '0358' '0375' '0362' '0351' '0368'
 '0366' '0334' '0374' '0320' '0339' '0363']
eLot Sort ['D' nan 'A']

In [17]:
df.drop(columns_to_drop, axis=1).to_csv("../data/lovely-rita-clean.csv")

In [18]:
np.diff(np.where(df["Ticket Issue Time"].isnull()))

array([[40406, 35638, 90250,  1103,  6773,  8258,  1390,  2482,   449,
         5174,  1033,  9588,     1,  1300,  4477,  9044,   758,  6034,
        31667, 11143,  7311,     1,  1868,     1,     1,  9067,  2696,
          735,  3689,  3671, 13927, 13328,  4273, 13371,  6864,  8042,
            1,  1464, 37082, 36835, 12322,  9966, 27629, 29328,  7728,
        13391, 27953, 41120, 42521, 12638,  1399, 19646, 48881,  4325,
        19355,  1206,  2723, 16276, 12113, 22164,  7483, 42133, 18794,
         1220, 19722,  4681,  6293,  2300, 11099, 17565,  6906, 39864,
         5826,  2591, 75370, 19027,  5445, 16277,  7806,  1343,  7967,
         8926,  1279,  8922, 14177, 15508,   131,     1,     1,  5499,
        14047, 15032,  9828, 19247,     1, 26901, 14884,    15,  4089,
        21702, 21338, 29094, 32810,   723, 14745,  2108,  1571, 44630,
        17035, 30384,  9287, 26673,  7906, 12107, 12738, 27551, 13668,
         5654]])

In [63]:
for i in np.where(df["Ticket Issue Time"].isnull())[0]:
    prev_value = np.nan
    prev_index = i
    while type(prev_value) != str:
        prev_index -= 1
        prev_value = df.iloc[prev_index]["Ticket Issue Time"]
    #print type(prev_value)
    #print prev_value
    next_value = np.nan
    next_index = i
    while type(next_value) != str:
        next_index += 1
        next_value = df.iloc[next_index]["Ticket Issue Time"]
    diff = get_time_diff(prev_value, next_value)
    split_count = next_index-prev_index
    prev_minutes = convert_time_str_to_min(prev_value)
    for _ in range(split_count):
        prev_minutes += (diff / split_count)
        df.at[i, "Ticket Issue Time"] = convert_min_to_time_str(prev_minutes)

In [64]:
get_column_report(df)

,Column Name,Data Type,Unique Count,Sample Value,NaNs,% NaN
55,Ticket Issue Date,object,1827,1/1/12,0,0.00
38,RCI,object,3,Residential,0,0.00
36,Precision,object,5,Zip9,0,0.00
45,Street,object,174339,6100 OLD QUARRY LOOP,0,0.00
31,Longitude,float64,10575,-122.166,0,0.00
30,Latitude,float64,9324,37.7787,0,0.00
54,Summary,object,5,Match-Mailable,0,0.00
43,State,object,2,california,0,0.00
56,Ticket Issue Time,object,2872,10:30:00,0,0.00
57,Ticket Number,object,1645812,838880801,0,0.00
58,Time Zone,object,2,Pacific,0,0.00
62,Violation Description Long,object,87,OBEDIENCE TO SIGNS,0,0.00
42,Sequence,int64,347427,1,0,0.00
2,Badge Number,object,1461,937,0,0.00
63,Violation External Code,object,98,10.16.110,0,0.00
5,City,object,2,oakland,0,0.00
11,DPV Footnotes,object,9,AABB,21,0.00
44,State Abbreviation,object,2,CA,21,0.00
16,Delivery Line 1,object,164654,6100 Old Quarry Loop,21,0.00
32,Notes,object,64,"Standardized, Matched street and city and stat...",21,0.00
29,Last Line,object,20025,Oakland CA 94605-3376,21,0.00
6,City Name,object,3,Oakland,21,0.00
46,Street Name,object,8579,OLD QUARRY LOOP,25,0.00
24,Fine Amount,object,68,$73,408,0.02
48,Street Number,object,10859,6100,27800,1.69
51,Street Suffix,object,18,AVE,71187,4.33
14,DST,object,2,Y,219555,13.34
39,Record Type,object,4,S,219555,13.34
59,UTC Offset,object,2,-8,219555,13.34
4,Carrier Route,object,53,C026,219555,13.34
9,County Name,object,2,Alameda,219555,13.34
7,Congressional District,object,3,13,219555,13.34
47,Street Name 2,object,1263,Old Quarry,219555,13.34
8,County FIPS,object,2,06001,219555,13.34
19,Delivery Point Barcode,object,83474,946053376007,222599,13.53
64,Zip Type,object,3,Standard,222599,13.53
65,Zipcode,object,18,94605,222599,13.53
26,Full Zipcode,object,20024,94605-3376,222599,13.53
37,Primary Number,object,9223,6100,223544,13.58
35,Plus 4 Code,object,4324,3376,223588,13.59
12,DPV Match Code,object,5,Y,223588,13.59
52,Street Suffix 2,object,21,Loop,247585,15.04
0,Active,object,3,Y,648642,39.41
67,eLot Sort,object,3,D,648642,39.41
13,DPV Vacant,object,3,N,648642,39.41
66,eLot Sequence,object,377,0220,648642,39.41
18,Delivery Point,object,101,00,648642,39.41
20,Delivery Point Check Digit,object,11,7,648642,39.41
10,DPV Camera,object,3,N,648642,39.41
25,Footnotes,object,38,L#,995274,60.47
3,Building Default Indicator,object,2,Y,1422931,86.46
50,Street Predirection,object,5,E,1533810,93.19
15,Default City Name,object,3,Emeryville,1574641,95.68
40,Secondary Designator,object,11,Lot,1629637,99.02
27,LACS Link Code,object,3,00,1638024,99.53
28,LACS Link Indicator,object,3,N,1638024,99.53
49,Street Postdirection,object,5,E,1643655,99.87
41,Secondary Number,object,50,12,1644057,99.89
22,Extra Secondary Designator,object,2,Lot,1645788,100.00
1,Addressee,object,1,NaN,1645812,100.00
61,Urbanization,object,1,NaN,1645812,100.00
21,EWS Match,object,1,NaN,1645812,100.00
17,Delivery Line 2,object,1,NaN,1645812,100.00
53,Suite Link Match,object,1,NaN,1645812,100.00
23,Extra Secondary Number,object,1,NaN,1645812,100.00
34,PMB Number,object,1,NaN,1645812,100.00
60,Unnamed: 13,object,1,NaN,1645812,100.00
33,PMB Designator,object,1,NaN,1645812,100.00